### PR TITLE
Added support for write permission in Stash.

### PR DESCRIPTION
**Pull request by wesmiles**
I needed the ability to auto deploy keys into Stash with READ and WRITE permissions.

Have updated code to cater for this.

Thanks
Wes

### CODE REVIEW

**Comment by abrader** [comment]
@wesmiles This is because you need the deploy key to perform actions like code promotion/merges?

**Comment by wesmiles** [comment]
We need to add to automatically add/update files in our Stash repo as the user in the git_deploy_key call as opposed to just cloning the repo.  Cheers

**Comment by wesmiles** [comment]
Hi, will you be able to merge the PR? Thanks

**Comment by abrader** [comment]
@wesmiles Need to review since you've added the supporting code for Stash only I need to consider other providers.  Plus write_permission seems redundant, should probably just be permission.  Lastly, we are not sure it is a good idea to promote the use of deploy keys with write permissions since these keys cannot have passphrases and therefore are more vulnerable (https://developer.github.com/guides/managing-deploy-keys/#deploy-keys).  Granted it can be up to the user and we just call out the caveats in the README. Will take a look ASAP and I will get back to you.

**Pull request closed without merging**
